//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public int cid { get; set; }
        public string title { get; set; }
        public string book { get; set; }
        public Nullable<int> price { get; set; }
        public string author { get; set; }
        public string Cimage { get; set; }
    }
}
